cd "%systemroot%\system32\CARMELIX"
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
start REBOOT.exe
